import { expect, test } from '@playwright/test'

test('教师可创建填空题并按知识点自动组题', async ({ page }) => {
  const suffix = Date.now().toString().slice(-6)
  await page.goto('/login')
  await page.locator('input.el-input__inner').nth(0).fill('800001')
  await page.locator('input.el-input__inner').nth(1).fill('123456')
  await page.getByRole('button', { name: '进入系统' }).click()
  await page.waitForURL('**/dashboard')

  await page.goto('/exam/questions')
  await page.getByRole('button', { name: '新建题目' }).click()
  const dialog = page.getByRole('dialog', { name: '新建题目' })
  await dialog.getByLabel('题目编码').fill(`TK-${suffix}`)
  await dialog.getByLabel('学科').fill('语文')
  await dialog.locator('.grid-three .el-form-item').nth(2).locator('.el-select').click()
  await page.locator('.el-select-dropdown__item').filter({ hasText: '填空题' }).last().click()
  await dialog.getByLabel('知识点').fill('现代文阅读')
  await dialog.getByLabel('题干（纯文本）').fill('请依次填写作者、作品。')
  await dialog.getByLabel('题干富文本 HTML（基础版）').fill('<p>请依次填写<strong>作者</strong>、作品。</p>')
  await expect(page.getByText('题干富文本预览')).toBeVisible()
  await dialog.getByLabel('选项 / 填空位 JSON').fill('["第1空","第2空"]')
  await dialog.getByLabel(/答案说明：/).fill('鲁迅|呐喊')
  await dialog.getByRole('button', { name: '保存' }).click()
  await expect(page.getByText('题目已创建')).toBeVisible()
  await expect(page.getByText(`TK-${suffix}`)).toBeVisible()

  await page.getByRole('button', { name: '按知识点自动组题' }).click()
  const knowledgeDialog = page.getByRole('dialog', { name: '按知识点自动组题（基础版）' })
  await knowledgeDialog.getByLabel('学科').fill('语文')
  await knowledgeDialog.getByLabel('知识点配额').fill('现代文阅读,1')
  await knowledgeDialog.getByRole('button', { name: '生成候选题组' }).click()
  await expect(page.getByText('已按知识点生成')).toBeVisible()
  await expect(knowledgeDialog.getByRole('cell', { name: '现代文阅读' }).first()).toBeVisible()
})
